; [servers]
; 192.168.56.110 ansible_user=vagrant ansible_ssh_private_key_file=/home/vagrant/.ssh/id_rsa

[local]
vagrant ansible_host=192.168.33.10 ansible_user=vagrant

[digitalocean]
inception ansible_host=134.209.67.154 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3