
- hosts: server
  become: true
  
  roles:
    - ./roles/droplet

- hosts: created_droplets
  become: true

  roles:
    - ./roles/setup
    - ./roles/database
    # - ./roles/webserver
    # - ./roles/wordpress