- name: Delete existing Droplet
  community.digitalocean.digital_ocean_droplet:
    state: absent
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
    name: inception
    unique_name: true

- name: Delete existing domain records
  community.digitalocean.digital_ocean_domain:
    state: absent
    name: obeaj.com
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
  ignore_errors: yes

- name: Wait for deletion to complete
  ansible.builtin.pause:
    seconds: 30

- name: Create a new Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
    name: inception
    unique_name: true
    size: s-1vcpu-1gb
    region: sfo3
    image: ubuntu-20-04-x64
    wait_timeout: 500
    ssh_keys: [ '29:75:f5:6a:07:49:94:28:e3:ed:a7:60:61:0c:9f:ea', 'a2:27:50:c9:1f:8f:dd:75:08:c5:2d:e4:97:33:2c:e8' ]
  register: inception

- name: Show Droplet info
  ansible.builtin.debug:
    msg: |
      Droplet ID is {{ inception.data.droplet.id }}
      First Public IPv4 is {{ (inception.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address | default('<none>', true) }}
      First Private IPv4 is {{ (inception.data.droplet.networks.v4 | selectattr('type', 'equalto', 'private')).0.ip_address | default('<none>', true) }}

- name: Add Droplet to Ansible inventory
  add_host:
    name: "{{ (inception.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address }}"
    groups: created_droplets
    ansible_user: root
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"

- name: Add domain to DigitalOcean
  community.digitalocean.digital_ocean_domain:
    state: present
    name: obeaj.com
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"

- name: Add A record for root domain
  community.digitalocean.digital_ocean_domain_record:
    state: present
    domain: obeaj.com
    type: A
    name: "@"
    data: "{{ (inception.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address }}"
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"

- name: Add A record for www subdomain
  community.digitalocean.digital_ocean_domain_record:
    state: present
    domain: obeaj.com
    type: A
    name: "www"
    data: "{{ (inception.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address }}"
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"

- name: Verify domain records
  community.digitalocean.digital_ocean_domain_record_info:
    domain: obeaj.com
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
  register: domain_records

- name: Display domain records
  debug:
    var: domain_records
